CREATE TABLE PRODUCT (PRODUCT_ID INTEGER (5) PRIMARY KEY, PRODUCT_NAME VARCHAR (10), PRODUCT_DESCRIPTION VARCHAR (50), QUANTITY INTEGER (3));

INSERT INTO PRODUCT VALUES (1, 'lorem', 'lorem ipsum', 4);
INSERT INTO PRODUCT VALUES (2, 'dolor', 'dolor sit', 12);